import Providers from '@/components/Providers';
import type { Metadata } from "next";
import { Toaster } from "sonner";
import "./globals.css";
import Navbar from '@/components/Navbar';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Providers>
        <Toaster richColors />
        <Navbar />
        <main>
          {children}
        </main>
        </Providers>
      </body>
    </html>
  );
}
